apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opencost
  name: opencost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        app: opencost
    spec:
      serviceAccountName: opencost
      containers:
      - env:
          - name: PROMETHEUS_SERVER_ENDPOINT
            value: http://prometheus-server.prometheus.svc" # The endpoint should have the form http://<service-name>.<namespace-name>.svc
          - name: CLOUD_PROVIDER_API_KEY
            value: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U" # The GCP Pricing API requires a key. This is supplied just for evaluation.
          - name: CLUSTER_ID
            value: "cluster-one" # Default cluster ID to use if cluster_id is not set in Prometheus metrics.
        image: quay.io/kubecost1/kubecost-cost-model:latest
        imagePullPolicy: "Always"
        name: opencost
        ports:
        - containerPort: 9003
          name: opencost-9003
        resources:
          # limits:
          #   memory: "400Mi"
          #   cpu: "1"
          # requests:
          #   memory: "200Mi"
          #   cpu: ".5"        
      hostname: opencost
      restartPolicy: Always      
status: {}
