---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencost-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 20Gi