apiVersion: v1
kind: Service
metadata:
  labels:
    app: opencost
  name: opencost
spec:
  ports:
  - name: opencost-9003
    port: 9003
    targetPort: 9003
  selector:
    app: opencost
status:
  loadBalancer: {}